# This is a basic workflow to help you get started with Actions

name: Build_Test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # Run on Ubuntu
    runs-on: ubuntu-latest

    # Steps run actions, currently only a build is needed
    steps:
    
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Give gradle permissions
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      
      # Builds robot code
      - name: Build Code
        run: ./gradlew build

      
